### ISSUE TITLE
gajira-login returns `Jira API error`

### ISSUE THREAD

**Issue by victorfgs** [atlassian/gajira-login#18]
I currently set a gh-action on my repo as instructed [here](https://github.com/namin2/dependabot_jira/blob/master/dependabot_jira.yml). 

The action returns a 401 http response with a body message `Basic authentication with passwords is deprecated (...)`.
Am I doing something wrong here or the gh-action should be updated to a new login method?

**Comment by patrickc91** [comment]
So...these plugins are basically dead right?

**Comment by luisiturrios1** [comment]
Create the encoded token in the format of base64Encode(<username>:<api_token>). For example, if the username is ci@example.com and the token is 954c38744be9407ab6fb, then ci@example.com:954c38744be9407ab6fb needs to be base64 encoded to form Y2lAZXhhbXBsZS5jb206OTU0YzM4NzQ0YmU5NDA3YWI2ZmI=

**Comment by julien-herrero-tab** [comment]
Hi @danepowell , I've tried with your fork (`danepowell/gajira-login@bearer`) but I still have a **401 Unauthorized**

```
    status: 401,
    body: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>401</status-code><message>Client must be authenticated to access this resource.</message></status>'
    ```
 
Do I have to do some thing in particular to make it work ? I've also tried @luisiturrios1 suggestion, still failing.

My token is OK with curl, with a JIRA cloud server for information.

**Comment by julien-herrero-tab** [comment]
Well, after some investigation I'm not sure but I guess we need to configure [PAT](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) for Bearer usage. Unfortunately unavailable on my Jira Cloud...

Finally, my journey has ended here: https://github.com/atlassian/gajira-login/compare/master...acquia:server aka `acquia/gajira-login@server` (thanks again @danepowell !). With downgrading to the rest API version, we can use again MAIL+API_TOKEN authentication. 
That's a shame, and I don't know if it's sustainable, but it seems working for now 🤷

**Comment by danepowell** [comment]
I've thoroughly confused myself at this point trying to sort out every combination of install type (server / cloud), api version (2/3), and authentication method (bearer, basic, token, password...)

But I think if you want to use mail + token (or is it mail + password?) via Basic authentication and server install, you should use the `server` branches of these packages:
- https://github.com/acquia/gajira-login
- https://github.com/acquia/gajira-create

If you want to use personal access tokens (i.e. bearer authentication), use the `bearer` branches of those packages.

I no longer maintain my personal forks (danepowell/gajira-login and danepowell/gajira-create).

**Comment by mboudreau** [comment]
This actions still works as shown with our own actions that runs on every push and logs into Jira cloud.

I did get into a similar issue by using _the wrong API tokens_.  As per the documentation, [follow the instructions here to how to get the correct API tokens](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/) to be used in this action.

I'll close this ticket for now unless there's something else not working with it.

**Comment by danepowell** [comment]
I apologize that I can't recall the full history of this issue, but the current problem for me is that our Jira instance only supports personal access tokens, hence the need for our fork at https://github.com/acquia/gajira-login
