### ISSUE TITLE
Jira server support?

### ISSUE THREAD

**Issue by f4nha** [atlassian/gajira-login#29]
HI team, any expectation to have this gajira-login to support JIRA Server instances, using PAT tokens?

**Comment by martinm82** [comment]
Actually what is the reason why Jira Server is not supported? The API seems to be the same, right?

**Comment by mboudreau** [comment]
@martinm82 @f4nha You're right, it should work, but someone added API version 3 which Jira Server doesn't support.  I've created a branch that uses version 2 instead.  Do you mind trying it out by setting your actions to `gajira-login@more-fixes` and see if it works for you?

**Comment by mboudreau** [comment]
I've updated the API version, it should now work for jira server as long as you use the correct api tokens :)
