### ISSUE TITLE
"Logged in as: undefined" even though login works

### ISSUE THREAD

**Issue by Piedone** [atlassian/gajira-login#30]
I'm reporting the same issue: https://github.com/atlassian/gajira-login/issues/7 However, the original author closed it, despite it still being an issue.

**Comment by jontg** [comment]
If you take a closer look at the code itself, [the code](https://github.com/atlassian/gajira-login/blob/master/action.js#L19) tries to log out the `name` field of the [payload](https://github.com/atlassian/gajira-login/blob/master/common/net/Jira.js#L14-L19) of `/rest/api/3/myself`.  However... https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/ that field was deprecated.

**Comment by mboudreau** [comment]
I've updated the action to only display "Logged in Successfully" when it works.

**Comment by Piedone** [comment]
Thank you!
