### ISSUE TITLE
Login job fails with 401 Unauthorized error. 

### ISSUE THREAD

**Issue by 1sakov** [atlassian/gajira-login#39]
Hey guys. 
I've added all three params in ci workflow:
JIRA_BASE_URL: https://p2pvalidator.atlassian.net
JIRA_USER_EMAIL: $JIRA_USER_EMAIL
JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

but it fails with 401. 

I checked with postman - it works, the JIRA_API_TOKEN is valid. 

According to this job, there are headers null. looks like my api token is not setting. Can you help me please? 

https://github.com/p2p-org/key-app-android/actions/runs/3956087771/jobs/6774957106

**Comment by Z4ck404** [comment]
@1sakov why did you close this issue, i have the same problem :( 
the token is valid but fails when tested with the workflow
